### ISSUE TITLE
ditto variables not working

### ISSUE THREAD

**Issue by nethan-freely** [dittowords/ditto-react#18] opened 2022-10-07 00:03 UTC
Hi we tried using interpolation variables for ditto components but it doesn't seem to be working. Any suggestion on what could be the issue?
https://github.com/dittowords/ditto-react#interpolation

we're using `"ditto-react": "^1.2.0",`

```
// examples of attempted use

const text = useDittoSingleText({
    textId: 'text_legal_stuff_item_4',
    variables: {
      PDS_LINK_CURRENT: 'testing',
      pds_link_current: 'what we get',
      pdsLinkCurrent: 'other',
    },
  });

 <DittoText
    textId="text_legal_stuff_item_4"
    variables={{
      PDS_LINK_CURRENT: 'testing',
      pds_link_current: 'what we get', 
      pdsLinkCurrent: 'other',
    }}
  />
  
    
// text doesn't interpolate and will print out the string below
({{PDS_LINK_CURRENT}})  {{pds_link_current}} {{pdsLinkCurrent}} for information
```

We tried running the local examples but text doesn't seem to show up either (see below)

thanks

![Screen Shot 2022-10-07 at 10 56 26 am](https://user-images.githubusercontent.com/112359152/194438957-f7c78bea-0ed3-4ad1-9e08-6948dd1ab9a7.png)

**Comment by azjgard** [comment] 2022-10-11 18:29
Hi @nethan-freely, thanks for opening this issue! It appears that this could be a case of unclear documentation on our part.

Variable interpolation in `ditto-react` only works with variables that have been created inside of Ditto; it appears from looking at your project that while you have the interpolation placeholders in your text, there are not variables associated with them. [This help guide](https://www.dittowords.com/docs/variables) should be helpful in illustrating how Ditto variables can be created and inserted into your text!

Can you create / confirm you've created Ditto variables for the text items that you're having issues with, and then re-run the `ditto-cli pull` command? This should solve your issue. If the issue persists, sharing the contents of your `ditto/config.yml` file will help us further debug!

> We tried running the local examples but text doesn't seem to show up either (see below)

If you've linked the Ditto CLI to your own workspace and overwritten the `ditto` output files, it makes sense that text wouldn't show up in the local examples, because the component and text ids that the local examples rely on would no longer exist.

---------------------------------------------

I've confirmed that things appear to be working on my end as follows:

**Text item in Ditto**
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/19500384/195170768-ebe77fdd-bb1a-47e5-b10f-27132eca9b33.png">


**ditto/config.yml**
```yml
projects:
  - name: My Project
    id: 6345ae6912d03cb4718e2a3a
```

**Application code**
```jsx
import DittoProvider, { useDittoSingleText } from "ditto-react";
import source from "./ditto";

function _App() {
  return (
    <DittoProvider source={source} projectId="project_6345ae6912d03cb4718e2a3a">
      <App />
    </DittoProvider>
  );
}

function App() {
  const text = useDittoSingleText({
    textId: "my_text_id",
    variables: {
      username: "Jordin",
    },
  });

  return <div className="App">{text}</div>;
}
```

**Result**
<img width="906" alt="image" src="https://user-images.githubusercontent.com/19500384/195170872-26f0fb2e-cb1b-441c-8cb7-df1d96acb59f.png">

**Comment by azjgard** [comment] 2022-10-17 14:22
@nethan-freely I made some small updates to hopefully clarify this issue in the README under the [Variable Interpolation](https://github.com/dittowords/ditto-react#variable-interpolation) section. I'm going to close this issue as resolved, but please feel free to reopen or create another if you run into further problems :)

**Closed by azjgard** 2022-10-17 14:22 UTC

**Comment by nethan-freely** [comment] 2022-10-28 02:46
Thanks, @azjgard. We tried it out and it worked with variables created in Ditto :)
